[package]
name = "lldap_model"
version = "0.1.0"
authors = ["Valentin Tolmer <valentin@tolmer.fr>", "Steve Barrau <steve.barrau@gmail.com>", "Thomas Wickham <mackwic@gmail.com>"]
edition = "2018"

[features]
js = []

[dependencies]
chrono = { version = "*", features = [ "serde" ]}
serde = "*"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.5", features = [ "runtime-actix-native-tls", "any", "sqlite", "mysql", "postgres", "macros" , "chrono"] }
