[package]
authors = ["Valentin Tolmer <valentin@tolmer.fr>", "Steve Barrau <steve.barrau@gmail.com>", "Thomas Wickham <mackwic@gmail.com>"]
edition = "2018"
name = "lldap"
version = "0.1.0"

[dependencies]
actix = "0.11.0-beta.3"
actix-rt = "2.1.0"
actix-server = "2.0.0-beta.3"
actix-service = "2.0.0-beta.4"
actix-web = "4.0.0-beta.3"
anyhow = "*"
clap = "3.0.0-beta.2"
futures = "*"
futures-util = "*"
http = "*"
ldap3_server = "*"
log = "*"
serde = "*"
sqlx = { version = "0.5", features = [ "runtime-actix-native-tls", "any", "sqlite", "mysql", "postgres", "macros" ] }
thiserror = "*"
tokio = { version = "1.2.0", features = ["full"] }
tokio-util = "0.6.3"
tracing = "*"
tracing-actix-web = "0.3.0-beta.2"
tracing-log = "*"
tracing-subscriber = "*"

[dependencies.figment]
features = ["toml", "env"]
version = "*"

[dev-dependencies]
mockall = "0.9.1"
