[package]
authors = ["Valentin Tolmer <valentin@tolmer.fr>", "Steve Barrau <steve.barrau@gmail.com>", "Thomas Wickham <mackwic@gmail.com>"]
edition = "2018"
name = "lldap"
version = "0.1.0"

[patch.crates-io]
actix-files = { git = "https://github.com/actix/actix-web", rev = "a9dc1586a0935c48c3f841761bf81c43ca9e2651" }
actix-http = { git = "https://github.com/actix/actix-web", rev = "a9dc1586a0935c48c3f841761bf81c43ca9e2651" }
actix-web = { git = "https://github.com/actix/actix-web", rev = "a9dc1586a0935c48c3f841761bf81c43ca9e2651" }

[dependencies]
actix = "0.11.1"
actix-files = "0.6.0-beta.4"
actix-http = "3.0.0-beta.6"
actix-rt = "2.2"
actix-server = "2.0.0-beta.5"
actix-service = "2.0.0"
actix-web = "4.0.0-beta.6"
anyhow = "*"
clap = "3.0.0-beta.2"
chrono = { version = "*", features = [ "serde" ]}
futures = "*"
futures-util = "*"
http = "*"
ldap3_server = "*"
log = "*"
serde = "*"
sqlx = { version = "0.5", features = [ "runtime-actix-native-tls", "any", "sqlite", "mysql", "postgres", "macros" , "chrono"] }
thiserror = "*"
tokio = { version = "1.2.0", features = ["full"] }
tokio-util = "0.6.3"
tracing = "*"
tracing-actix-web = "0.3.0-beta.2"
tracing-log = "*"
tracing-subscriber = "*"
async-trait = "0.1.48"
sea-query = { version = "0.9.4", features = [ "with-chrono" ] }
lldap_model = { path = "model" }
lldap_app = { path = "app" }
serde_json = "1.0.64"

[dependencies.figment]
features = ["toml", "env"]
version = "*"

[dev-dependencies]
mockall = "0.9.1"
