[package]
name = "lldap"
edition = "2018"
version = "0.1.0"
authors = [
  "Valentin Tolmer <valentin@tolmer.fr>",
  "Steve Barrau <steve.barrau@gmail.com>",
  "Thomas Wickham <mackwic@gmail.com>"
]

[dependencies]
clap = "3.0.0-beta.2"
actix-web = "3"
anyhow = "*"
thiserror="*"
http = "*"
passablewords = "*"
serde = "*"
tracing = "*"
tracing-actix-web = "*"
tracing-log = "*"
tracing-subscriber = "*"

[dependencies.figment]
features = ["toml", "env"]
version = "*"

[dev-dependencies]
actix-rt = "*"
