[package]
authors = ["Valentin Tolmer <valentin@tolmer.fr>", "Steve Barrau <steve.barrau@gmail.com>", "Thomas Wickham <mackwic@gmail.com>"]
edition = "2018"
name = "lldap"
version = "0.1.0"
[dependencies]
actix-web = "3"
anyhow = "*"
clap = "3.0.0-beta.2"
http = "*"
log = "*"
serde = "*"
thiserror = "*"
tracing = "*"
tracing-actix-web = "*"
tracing-log = "*"
tracing-subscriber = "*"

[dependencies.figment]
features = ["toml", "env"]
version = "*"

[dev-dependencies]
actix-rt = "*"
