[package]
name = "lldap_app"
version = "0.1.0"
authors = ["Valentin Tolmer <valentin@tolmer.fr>", "Steve Barrau <steve.barrau@gmail.com>", "Thomas Wickham <mackwic@gmail.com>"]
edition = "2018"

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2"
lldap_model = { path = "../model" }
anyhow = "1"
web-sys = { version = "0.3", features = [ "console", "Document", "Element", "HtmlDocument" ] }
serde_json = "1"
serde = "1"
http = "0.2.4"
jwt = "0.13"
chrono = "*"

[lib]
crate-type = ["cdylib"]
